### ISSUE TITLE
[Django 1.6.5] Syntax Error inside widgets.py on line 22

### ISSUE THREAD

**Issue by maxpaynestory** [praekelt/django-recaptcha#45] opened 2014-06-01 21:18 UTC
Change

<code>return mark_safe(u'%s' % client.displayhtml(self.public_key, self.js_attrs, use_ssl=self.use_ssl))</code>

To

<code>return mark_safe('%s' % client.displayhtml(self.public_key, self.js_attrs, use_ssl=self.use_ssl))</code>

**Comment by tolya373** [comment] 2015-11-14 03:18
The issue is actual for the Python 3.2. For example, Python 3.5 works fine.

**Comment by adamchainz** [comment] 2016-10-06 14:30
Python 3.2 is no longer supported, so I'm closing this.

**Closed by adamchainz** 2016-10-06 14:30 UTC
